// =================================================================================
// Code generated by GoFrame CLI tool. DO NOT EDIT.
// =================================================================================

package entity

import (
	"github.com/gogf/gf/v2/os/gtime"
)

// Rotation is the golang structure for table rotation.
type Rotation struct {
	Id       int         `json:"id"       description:""`
	PicUrl   string      `json:"picUrl"   description:""`
	Link     string      `json:"link"     description:""`
	Sort     string      `json:"sort"     description:""`
	CreateAt *gtime.Time `json:"createAt" description:""`
	UpdateAt *gtime.Time `json:"updateAt" description:""`
	DeleteAt *gtime.Time `json:"deleteAt" description:""`
}
